### ISSUE TITLE
UserApi problem with confirm

### ISSUE THREAD

**Issue by spid3r** [mean-expert-official/loopback-sdk-builder#147]
Hi guys,

first of all a big shout out to you all for building such a nice SDK for angular2! I love it!
You guys rock!

I found a problem on the UserApi confirm method:
[Loopback documentation](https://docs.strongloop.com/display/public/LB/User+REST+API#UserRESTAPI-Confirmemailaddress) defines the GET confirm request with **3 query params**:

- uid
- token 
- redirect

but the generated confirm method in Class UserApi only puts the token and redirect as urlParam and the **uid as a route param**:

```
  /**
   * Confirm a user registration with email verification token.
   *
   * @param string uid 
   *
   * @param string token 
   *
   * @param string redirect 
   *
   * @returns object An empty reference that will be
   *   populated with the actual data once the response is returned
   *   from the server.
   *
   * This method returns no data.
   */
  public confirm(uid: any, token: any, redirect: any = undefined): Observable<any> {
    let method: string = "GET";
    let url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
    "/users/confirm";
    let routeParams: any = {
      uid: uid
    };
    let postBody: any = {};
    let urlParams: any = {};
    if (token) urlParams.token = token;
    if (redirect) urlParams.redirect = redirect;
    let result = this.request(method, url, routeParams, urlParams, postBody);
    return result;
  }
```

This leads to an error which gets returned by loopback framework when calling the generated confirm method of UserApi:

> {
    "error": {
        "name": "Error",
        "status": 400,
        "message": "uid is a required argument",
        "statusCode": 400,
        "stack": "Error: uid is a required argument\n...
}

I think the problem can be found and solved 
[ here in loopback-sdk-builder/lib/angular2/index.js#526](https://github.com/mean-expert-official/loopback-sdk-builder/blob/d34cbc68ff4bdbf4a1e57a27746b1e9b4eda2cbe/lib/angular2/index.js#L526):  where you want to filter unallowed query params :
urlParams = urlParams.filter(param => (param.arg && !param.arg.match(/(**id**|fk|data|options|credentials)/g)));
so the filter is being applied to the function argument **uid** as well which leads to this problem.
Here is the Loopback Model definition of the confirm method:
```
/**
   * Confirm the user's identity.
   *
   * @param {Any} userId
   * @param {String} token The validation token
   * @param {String} redirect URL to redirect the user to once confirmed
   * @callback {Function} callback
   * @param {Error} err
   */
  User.confirm = function(uid, token, redirect, fn) {
    fn = fn || utils.createPromiseCallback();
    this.findById(uid, function(err, user) {
      if (err) {
        fn(err);
      } else {
        if (user && user.verificationToken === token) {
          user.verificationToken = null;
          user.emailVerified = true;
          user.save(function(err) {
            if (err) {
              fn(err);
            } else {
              fn();
            }
          });
        } else {
          if (user) {
            err = new Error(g.f('Invalid token: %s', token));
            err.statusCode = 400;
            err.code = 'INVALID_TOKEN';
          } else {
            err = new Error(g.f('User not found: %s', uid));
            err.statusCode = 404;
            err.code = 'USER_NOT_FOUND';
          }
          fn(err);
        }
      }
    });
    return fn.promise;
  };
```

**Comment by jonathan-casarrubias** [comment]
Hi @spid3r thanks for reaching out!!

Hey so, yes it seems that I will need to improve the regex to avoid other words containing id, like uid.

Thanks for contributing with this issue.

Cheers!!
Jon

**Comment by jonathan-casarrubias** [comment]
Fixed

**Comment by isrmicha** [comment]
still getting error in userApi.confirm, invalid token, anyone can help ?
